### ISSUE TITLE
./bin/data-api-endpoints <xxx> 2 doesn't work

### ISSUE THREAD

**Issue by tsmsogn** [movabletype/mt-data-api-sdk-js#3]
- mt-data-api-sdk-js Version: 0.1.0

### What I did

After I downloaded mt-data-api-sdk-js and installed node modules with `npm install`, I did following command.

```
./bin/data-api-endpoints <xxx> 2
```

### What happened

It raised following error.

```
/Users/tsmsogn/mt-data-api-sdk-js/bin/data-api-endpoints:14
    api     = new DataAPI({
              ^

TypeError: DataAPI is not a constructor
    at Object.<anonymous> (/Users/tsmsogn/mt-data-api-sdk-js/bin/data-api-endpoints:14:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
```

### What I expected to happen

I expect to it works like `./bin/data-api-endpoints <xxx> 1` and `./bin/data-api-endpoints <xxx> 3`.

**Comment by miniuchi** [comment]
Merged #4
